export const trebleClefQuestions = [
  {
    clefClass: "treble",
    note: "g",
    position: "100%",
    octaveIndex: 2,
  },
  {
    clefClass: "treble",
    note: "a",
    position: "95%",
    octaveIndex: 2,
  },
  {
    clefClass: "treble",
    note: "b",
    position: "90%",
    octaveIndex: 2,
  },
  {
    clefClass: "treble",
    note: "c",
    position: "85%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "d",
    position: "80%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "e",
    position: "75%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "f",
    position: "70%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "g",
    position: "65%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "a",
    position: "60%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "b",
    position: "55%",
    octaveIndex: 3,
  },
  {
    clefClass: "treble",
    note: "c",
    position: "50%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "d",
    position: "45%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "e",
    position: "40%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "f",
    position: "35%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "g",
    position: "30%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "a",
    position: "25%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "b",
    position: "20%",
    octaveIndex: 4,
  },
  {
    clefClass: "treble",
    note: "c",
    position: "15%",
    octaveIndex: 5,
  },
  {
    clefClass: "treble",
    note: "d",
    position: "10%",
    octaveIndex: 5,
  },
  {
    clefClass: "treble",
    note: "e",
    position: "5%",
    octaveIndex: 5,
  },
  {
    clefClass: "treble",
    note: "f",
    position: "0%",
    octaveIndex: 5,
  },
  {
    clefClass: "treble",
    note: "g",
    position: "-5%",
    octaveIndex: 5,
  },
  {
    clefClass: "treble",
    note: "a",
    position: "-10%",
    octaveIndex: 5,
  },
];

export const bassClefQuestions = [
  {
    clefClass: "bass",
    note: "b",
    position: "100%",
    octaveIndex: 0,
  },
  {
    clefClass: "bass",
    note: "c",
    position: "95%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "d",
    position: "90%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "e",
    position: "85%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "f",
    position: "80%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "g",
    position: "75%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "a",
    position: "70%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "b",
    position: "65%",
    octaveIndex: 1,
  },
  {
    clefClass: "bass",
    note: "c",
    position: "60%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "d",
    position: "55%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "e",
    position: "50%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "f",
    position: "45%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "g",
    position: "40%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "a",
    position: "35%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "b",
    position: "30%",
    octaveIndex: 2,
  },
  {
    clefClass: "bass",
    note: "c",
    position: "25%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "d",
    position: "20%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "e",
    position: "15%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "f",
    position: "10%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "g",
    position: "5%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "a",
    position: "0%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "b",
    position: "-5%",
    octaveIndex: 3,
  },
  {
    clefClass: "bass",
    note: "c",
    position: "-10%",
    octaveIndex: 4,
  },
];

export const allClefQuestions = [...trebleClefQuestions, ...bassClefQuestions]
